name: Terraform

description: terraform コマンドを実行する

inputs:
  command:
    description: plan もしくは apply
    required: true
  stage:
    description: stg もしくは prod
    required: true

runs:
  using: composite
  steps:
    - name: Select workspace
      shell: bash
      working-directory: terraform
      run: terraform workspace select ${{ inputs.stage }}

    - name: Exec terraform ${{ inputs.command }}
      shell: bash
      working-directory: terraform
      run: |
        terraform ${{ inputs.command }} \
          -var 'basicauth_username=${{ secrets.BASICAUTH_USERNAME }}' \
          -var 'basicauth_password=${{ secrets.BASICAUTH_PASSWORD }}'
