name: Test Firebase Security Rules

description: firebase のセキュリティルールのテスト

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: Save Yarn Cache
      uses: ./.github/actions/save-yarn-cache

    - name: Install Dependencies
      shell: bash
      working-directory: firebase
      run: yarn install --frozen-lockfile

    - name: Test firestore security rules
      shell: bash
      working-directory: firebase
      run: yarn run test:firestore
