name: Test Infra

description: インフラのテスト

inputs:
  aws-access-key-id:
    description: AWS アクセスキー ID
    required: true
  aws-secret-access-key:
    description: AWS シークレットアクセスキー
    required: true
  basicauth-username:
    description: Basic 認証のユーザー名
    required: false
  basicauth-password:
    description: Basic 認証のパスワード
    required: false

runs:
  using: composite
  steps:
    - name: Setup Terraform
      uses: ./.github/actions/setup-terraform
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
    - name: Exec terraform plan for stg
      uses: ./.github/actions/terraform
      with:
        stage: stg
        command: plan
        basicauth-username: ${{ inputs.basicauth-username }}
        basicauth-password: ${{ inputs.basicauth-password }}
    - name: Exec terraform plan for prod
      uses: ./.github/actions/terraform
      with:
        stage: prod
        command: plan
