name: Test Frontend

description: フロントエンドのテスト

runs:
  using: composite
  steps:
    - name: Build Frontend
      uses: ./.github/actions/build-frontend
      with:
        stage: test
        firebase-api-key: FIREBASE_API_KEY
        firebase-auth-domain: FIREBASE_AUTH_DOMAIN
        firebase-project-id: FIREBASE_PROJECT_ID
        firebase-storage-bucket: FIREBAsE_STORAGE_BUCKET
        firebase-messaging-sender-id: FIREBASE_MESSAGING_SENDER_ID
        firebase-app-id: FIREBASE_APP_ID

    - name: Test
      working-directory: frontend
      shell: bash
      run: yarn run test

    - name: Lint
      working-directory: frontend
      shell: bash
      run: yarn run lint
