name: build

on:
  workflow_call:
    inputs:
      stage:
        required: true
        type: string
    secrets:
      AWS_IAM_ROLE_ARN:
        required: true
      BASICAUTH_USERNAME:
        required: true
      BASICAUTH_PASSWORD:
        required: true

jobs:
  firestore_security_rules_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: firebase
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: firebase/yarn.lock
      - name: install dependencies
        run: yarn install --frozen-lockfile

      - name: run firestore security rules test
        run: yarn run test:firestore

  terraform_plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: us-east-1

      - name: run terraform plan
        run: |
          terraform init
          terraform workspace select ${{ inputs.stage }}
          terraform plan \
            -var 'basicauth_username=${{ secrets.BASICAUTH_USERNAME }}' \
            -var 'basicauth_password=${{ secrets.BASICAUTH_PASSWORD }}'

  frontend_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: frontend/yarn.lock
      - name: install dependencies
        run: yarn install --frozen-lockfile

      - name: build
        run: yarn run build
      - name: lint
        run: yarn run lint
      - name: test
        run: yarn run test
