name: deploy

on:
  workflow_call:
    inputs:
      stage:
        required: true
        type: string
    secrets:
      firebase-token:
        required: true

jobs:
  firebase_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: firebase
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: firebase/yarn.lock
      - name: install dependencies for firebase
        run: yarn install --frozen-lockfile
      # TODO: キャッシュを効かせる
      - name: install dependencies for function
        working-directory: firebase/functions
        run: yarn install --frozen-lockfile

      - name: deploy
        run: yarn run deploy --project ${{ inputs.stage }} --token ${{ secrets.firebase-token }}

  terraform_apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: us-east-1

      - name: run terraform plan
        run: |
          terraform init
          terraform workspace select ${{ inputs.stage }}
          terraform apply -auto-approve \
            -var 'basicauth_username=${{ secrets.basicauth-username }}' \
            -var 'basicauth_password=${{ secrets.basicauth-password }}'
