name: build for stg

on:
  push:
    branches:
      - develop

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    secrets: inherit
    with:
      stage: stg

  deploy:
    uses: ./.github/workflows/_deploy.yml
    secrets: inherit
    needs:
      - build
    with:
      stage: stg
