name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    secrets: inherit
    with:
      stage: prod

  deploy:
    uses: ./.github/workflows/_deploy.yml
    secrets: inherit
    needs:
      - build
    with:
      stage: prod
