name: build for stg

on:
  push:
    branches:
      - develop

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      env: stg
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      basicauth-username: ${{ secrets.BASICAUTH_USERNAME }}
      basicauth-password: ${{ secrets.BASICAUTH_PASSWORD }}
