name: Deploy to stg

on:
  push:
    branches:
      - develop

jobs:
  deploy_firebase:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: firebase
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-v1-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies for firebase
        run: yarn install --frozen-lockfile
      - name: Install Dependencies for functions
        working-directory: firebase/functions
        run: yarn install --frozen-lockfile

      - name: Deploy
        run: yarn run deploy --project stg --token ${{ secrets.FIREBASE_TOKEN }}

  deploy_infra:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Terraform init
        run: terraform init
      - name: Select workspace
        run: terraform workspace select stg
      - name: Terraform apply
        # TODO: apply にする
        run: |
          terraform plan \
            -var 'basicauth_username=${{ secrets.STG_BASICAUTH_USERNAME }}' \
            -var 'basicauth_password=${{ secrets.STG_BASICAUTH_PASSWORD }}'

  deploy_frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: frontend/yarn.lock
          node-version: 16.x
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create dotenv
        run: |
          echo "VITE_STAGE=\"stg\""                                                                     > .env
          echo "VITE_FIREBASE_API_KEY=\"${{ secrets.STG_FIREBASE_API_KEY }}\""                         >> .env
          echo "VITE_FIREBASE_AUTH_DOMAIN=\"${{ secrets.STG_FIREBASE_AUTH_DOMAIN }}\""                 >> .env
          echo "VITE_FIREBASE_PROJECT_ID=\"${{ secrets.STG_FIREBASE_PROJECT_ID }}\""                   >> .env
          echo "VITE_FIREBASE_STORAGE_BUCKET=\"${{ secrets.STG_FIREBASE_STORAGE_BUCKET }}\""           >> .env
          echo "VITE_FIREBASE_MESSAGING_SENDER_ID=\"${{ secrets.STG_FIREBASE_MESSAGING_SENDER_ID }}\"" >> .env
          echo "VITE_FIREBASE_APP_ID=\"${{ secrets.STG_FIREBASE_APP_ID }}\""                           >> .env
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn run build
      - name: Upload to S3
        run: aws s3 sync --delete ./dist s3://todo-box-stg-frontend
