name: Deploy to stg

on:
  push:
    branches:
      - main

jobs:
  deploy_firebase:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: firebase
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: 16.x

      - name: Install dependencies for firebase
        run: yarn install --frozen-lockfile
      - name: Install dependencies for functions
        working-directory: firebase/functions
        run: yarn install --frozen-lockfile

      - name: Deploy
        run: yarn run deploy --project stg --token ${{ secrets.FIREBASE_TOKEN }}
